/* Default 2026 tour dates — used to seed the `events` table the first time
   it's read (admin can then add/edit/remove freely). Server-side only. */
export const DEFAULT_EVENTS = [
  { id: "t1", date: "2026-06-01", city: "Ibiza", country: "ES", venue: "Hï Ibiza", region: "Europe", status: "Tickets", tickets: "https://www.hiibiza.com/events-calendar", cap: 20 },
  { id: "t2", date: "2026-06-05", city: "Monte Carlo", country: "MC", venue: "Nikki Beach — F1 Grand Prix", region: "Europe", status: "Tickets", tickets: "", cap: 15 },
  { id: "t3", date: "2026-06-06", city: "Monte Carlo", country: "MC", venue: "Private Party", region: "Europe", status: "Private", tickets: "", cap: 0 },
  { id: "t4", date: "2026-06-07", city: "Ibiza", country: "ES", venue: "Mestiza · Hï Ibiza", region: "Europe", status: "Tickets", tickets: "https://www.hiibiza.com/events/2026/mestiza", cap: 20 },
  { id: "t5", date: "2026-06-12", city: "Porto Cervo", country: "IT", venue: "Twiga · Sardinia", region: "Europe", status: "Tickets", tickets: "", cap: 18 },
  { id: "t6", date: "2026-06-14", city: "Costa da Caparica", country: "PT", venue: "Maresia Intimate Festival", region: "Europe", status: "Tickets", tickets: "", cap: 25 },
  { id: "t7", date: "2026-06-15", city: "Ibiza", country: "ES", venue: "Hï Ibiza", region: "Europe", status: "Tickets", tickets: "https://www.hiibiza.com/events-calendar", cap: 20 },
  { id: "t8", date: "2026-06-18", city: "Lisbon", country: "PT", venue: "SunceBeat", region: "Europe", status: "Tickets", tickets: "", cap: 20 },
  { id: "t9", date: "2026-06-19", city: "London", country: "GB", venue: "Ministry of Sound", region: "Europe", status: "Tickets", tickets: "https://www.ministryofsound.com/whats-on/", cap: 25 },
  { id: "t10", date: "2026-06-20", city: "Yeni İskele", country: "CY", venue: "Pera Mackenzie", region: "Europe", status: "Tickets", tickets: "", cap: 20 },
  { id: "t11", date: "2026-06-26", city: "Paris", country: "FR", venue: "l’Envol", region: "Europe", status: "Tickets", tickets: "", cap: 20 },
  { id: "t12", date: "2026-06-27", city: "Stuttgart", country: "DE", venue: "Zubrovka House Festival", region: "Europe", status: "Tickets", tickets: "", cap: 25 },
  { id: "t13", date: "2026-06-29", city: "Mykonos", country: "GR", venue: "Cavo", region: "Europe", status: "Tickets", tickets: "", cap: 18 },
  { id: "t14", date: "2026-07-02", city: "Casablanca", country: "MA", venue: "Cazaloka", region: "Africa", status: "Tickets", tickets: "", cap: 20 },
  { id: "t15", date: "2026-07-03", city: "Ibiza", country: "ES", venue: "Chinois", region: "Europe", status: "Tickets", tickets: "", cap: 20 },
  { id: "t16", date: "2026-07-04", city: "Jesolo Lido", country: "IT", venue: "King’s Club", region: "Europe", status: "Tickets", tickets: "", cap: 20 },
  { id: "t17", date: "2026-07-09", city: "Saint-Tropez", country: "FR", venue: "Naomad", region: "Europe", status: "Tickets", tickets: "", cap: 15 },
  { id: "t18", date: "2026-07-10", city: "Alanya", country: "TR", venue: "Sundaze Beach Club", region: "Europe", status: "Tickets", tickets: "", cap: 20 },
  { id: "t19", date: "2026-07-11", city: "Ibiza", country: "ES", venue: "Hï Ibiza", region: "Europe", status: "Tickets", tickets: "https://www.hiibiza.com/events-calendar", cap: 20 },
  { id: "t20", date: "2026-07-17", city: "Boom", country: "BE", venue: "Tomorrowland", region: "Europe", status: "Tickets", tickets: "https://www.tomorrowland.com/", cap: 30 },
  { id: "t21", date: "2026-07-18", city: "Tivat", country: "ME", venue: "Aura Beach", region: "Europe", status: "Tickets", tickets: "", cap: 20 },
  { id: "t22", date: "2026-07-24", city: "Bucharest", country: "RO", venue: "Nebula", region: "Europe", status: "Tickets", tickets: "", cap: 25 },
  { id: "t23", date: "2026-07-25", city: "Marseille", country: "FR", venue: "Delta Festival", region: "Europe", status: "Tickets", tickets: "", cap: 30 },
  { id: "t24", date: "2026-07-29", city: "Alta Rocca", country: "FR", venue: "L’Alta Rocca", region: "Europe", status: "Tickets", tickets: "", cap: 18 },
  { id: "t25", date: "2026-07-30", city: "Tunis", country: "TN", venue: "Calypso", region: "Africa", status: "Tickets", tickets: "", cap: 20 },
];
